apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP
  labels:
    app: $APP
spec:
  selector:
    matchLabels:
      app: $APP
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP
    spec:
      nodeSelector:
        role: bots
      containers:
        - image: $IMAGE
          name: $APP
          resources:
            requests:
              cpu: "5m"
              memory: 5Mi
          env:
            - name: "VERSION"
              value: "$VERSION"
            - name: "$ENV_1_NAME"
              value: "$ENV_1_VALUE"
            - name: "$ENV_2_NAME"
              value: "$ENV_2_VALUE"
            - name: "$ENV_3_NAME"
              value: "$ENV_3_VALUE"
            - name: "$ENV_4_NAME"
              value: "$ENV_4_VALUE"
            - name: "$ENV_5_NAME"
              value: "$ENV_5_VALUE"
